language: python

python:
  - "2.7"
  - "3.3"

# command to install dependencies
install: pip install coveralls

# command to run tests
script: coverage run --source=microschema setup.py test

# command to run after a successful build
after_success: coveralls
